### ISSUE TITLE
Error on jest

### ISSUE THREAD

**Issue by hayesleech** [FormidableLabs/nuka-carousel#598]
# Bugs and Questions

### Describe Your Environment

- What version of nuka-carousel are you using?
4.5.12
- What version of React are you using?
16.10.1
- What browser are you using?
it doesn't matter
- What machine are you on?
macbook

### Describe the Problem

I try to run a test with this package in my project. I use `jest` as the tester. 

Here is my `index.test.js`:
```jsx
import React from 'react';
import renderer from 'react-test-renderer';
import Carousel from 'nuka-carousel';

const test = renderer.create(
    <Carousel>
      <img key={1} src="https://via.placeholder.com/400/ffffff/c0392b/&text=slide1" />
      <img key={2} src="https://via.placeholder.com/400/ffffff/c0392b/&text=slide2" />
      <img key={3} src="https://via.placeholder.com/400/ffffff/c0392b/&text=slide3" />
      <img key={4} src="https://via.placeholder.com/400/ffffff/c0392b/&text=slide4" />
      <img key={5} src="https://via.placeholder.com/400/ffffff/c0392b/&text=slide5" />
      <img key={6} src="https://via.placeholder.com/400/ffffff/c0392b/&text=slide6" />
    </Carousel>
);

test('Carousel', () => expect(test).toBeDefined());
```

and it returns error:
```sh
Test suite failed to run

    TypeError: Cannot read property 'childNodes' of null

      3 | import Carousel from 'nuka-carousel';
      4 | 
    > 5 | const test = renderer.create(
        |                       ^
      6 |     <Carousel>
      7 |       <img key={1} src="https://via.placeholder.com/400/ffffff/c0392b/&text=slide1" />
      8 |       <img key={2} src="https://via.placeholder.com/400/ffffff/c0392b/&text=slide2" />

      at Carousel.getChildNodes (node_modules/nuka-carousel/lib/index.js:960:25)
      at Carousel.calcSlideHeightAndWidth (node_modules/nuka-carousel/lib/index.js:881:29)
      at Carousel.setDimensions (node_modules/nuka-carousel/lib/index.js:928:41)
      at Carousel.componentDidMount (node_modules/nuka-carousel/lib/index.js:172:12)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10930:22)
      at commitLayoutEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13583:7)
      at HTMLUnknownElement.callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10487:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.invokeGuardedCallbackDev (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10537:16)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10590:31)
      at commitRootImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13355:9)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:643:12)
      at runWithPriority (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1887:10)
      at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13184:3)
      at runRootCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12420:20)
      at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1935:24
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:643:12)
      at runWithPriority (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1887:10)
      at flushSyncCallbackQueueImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1931:7)
      at flushSyncCallbackQueue (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1920:3)
      at scheduleUpdateOnFiber (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12297:9)
      at scheduleRootUpdate (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15087:3)
      at updateContainerAtExpirationTime (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15115:10)
      at updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15134:10)
      at Object.create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15824:5)
      at Object.create (src/component/Carousel/nukaCarousel.test.jsx:5:23)
```

Is this issue related to `nuka-carousel`?

**Comment by dawidk92** [comment]
I have the same problem. These are errors I get:
- `Error: Uncaught [TypeError: Cannot read property 'childNodes' of null] at reportException [...]
TypeError: Cannot read property 'childNodes' of at Carousel.getChildNodes`
- `Error: Uncaught [ReferenceError: MutationObserver is not at reportException [...] ReferenceError: MutationObserver is not at Carousel.disconnectChildNodesMutationObserver`


Besides that I also get this warning:
- `Warning: componentWillReceiveProps has been renamed, and is not recommended for use.`

**Comment by dawidk92** [comment]
@hayesleech did you figure out how to solve this problem?

**Comment by hayesleech** [comment]
@dawidk92 No, I am still seeking for advices and solution

**Comment by michalv8** [comment]
I have managed to fix this by adding `createNodeMock` callback which creates fake ref objects. I'm using `multiSnapshotWithOptions` to initialize snapshots but it's the same with `snapshotWithOptions`. First I check which story is being processed and then I look for particular DOM element I need to mock. In this case it was `div` with class `slider-frame`.

```
initStoryshots({
  storyKindRegex: /^components/,
  test: multiSnapshotWithOptions(story => ({
    createNodeMock: element => {
      if (story.name === "MyStory") {
        if (element.type === "div" && element.props.className === 'slider-frame') {
          return {
            childNodes: [
              {
                childNodes: [{}]
              }
            ]
          };
        }
      }

      return null;
    }
  }))
});
```

I also needed to mock `MutationObserver` (I did it in `setupTests.js`):
```
global.MutationObserver = class {
  constructor(callback) {}
  disconnect() {}
  observe(element, initObject) {}
};
```

React docs also mentions how to mock ref objects in snapshot testing (old post but still valid) https://reactjs.org/blog/2016/11/16/react-v15.4.0.html#mocking-refs-for-snapshot-testing

**Comment by dannyvassallo** [comment]
I was able to mock it in my jest setup piggy-backing @michalv8 's solution like this:

```
global.MutationObserver = class {
  constructor(callback) {}
  disconnect() {}
  observe(element, initObject) {}
}
jest.mock('nuka-carousel', () => ({
  __esModule: true,
  ...require.requireActual('nuka-carousel'),
  default: ({ children }) => (
    <div className='mocked-nuka-carousel'>
      { children }
    </div>
  ),
}))
```

Worked to render children in snapshots.

**Comment by sarmeyer** [comment]
Is this still an issue for anyone? Since there are a couple solutions posted above, I will close this for now. If it remains an issue, please reopen
